/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_SAR_Seq_1.h"
#include "Sensor.h"
#include "Sensor_aliases.h"
#include "PWM_1.h"
#include "Clock_1.h"
#include "Clock_2.h"
#include "PWM_2.h"
#include "LED_1.h"
#include "LED_1_aliases.h"
#include "LED_2.h"
#include "LED_2_aliases.h"
#include "Pin_1.h"
#include "Pin_1_aliases.h"
#include "Red1.h"
#include "Red1_aliases.h"
#include "Blue1.h"
#include "Blue1_aliases.h"
#include "Green1.h"
#include "Green1_aliases.h"
#include "Red2.h"
#include "Red2_aliases.h"
#include "Blue2.h"
#include "Blue2_aliases.h"
#include "Green2.h"
#include "Green2_aliases.h"
#include "Switch1.h"
#include "Switch1_aliases.h"
#include "Clock_3.h"
#include "PWM_3.h"
#include "Speaker.h"
#include "Speaker_aliases.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "ADC_SAR_Seq_1_intClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

